const Database = require('better-sqlite3');
const db = new Database('/app/data/attributions.db');

const ins = db.prepare('INSERT OR REPLACE INTO aa (aa_code, aa_num, ue_num, cours_code, description) VALUES (?, ?, ?, ?, ?)');
const tx = db.transaction((rows) => { for (const r of rows) ins.run(r.code, r.num, r.ue, r.cours, r.desc); });

const rows = [
  {code:`AA282.1`,num:1,ue:282,cours:null,desc:`d’exploiter les notions, les concepts et les modèles abordés, basés sur l’approche globale du patient et de son entourage, en vue d’établir une communication adaptée et de créer une relation de travail efficace ;`},
  {code:`AA282.2`,num:2,ue:282,cours:null,desc:`de mettre en pratique les règles essentielles d’intervention utiles aux premiers secours et de lancer un appel aux services d’urgences.`},
  {code:`AA286.1`,num:1,ue:286,cours:null,desc:`de résoudre des problèmes portant sur des situations relatives à l’optique et à des systèmes optiques en appliquant les règles de calcul, les formules et les lois pertinentes sur le plan opératoire et de valider les résultats obtenus par une méthode de contrôle`},
  {code:`AA286.2`,num:2,ue:286,cours:null,desc:`de décrire les caractéristiques de la lumière dans un phénomène optique`},
  {code:`AA291.1`,num:1,ue:291,cours:null,desc:`d’expliquer le(s) type(s) d’amétropie ;`},
  {code:`AA291.2`,num:2,ue:291,cours:null,desc:`d’expliquer et de mettre en œuvre pour chaque étape de la réfraction une stratégie d’analyse et d’interprétation des résultats et de choisir la solution la plus appropriée ;`},
  {code:`AA291.3`,num:3,ue:291,cours:null,desc:`d’appliquer les normes d’hygiène et de sécurité en contactologie, en s’appuyant sur les principes et les lois de la microbiologie ;`},
  {code:`AA291.4`,num:4,ue:291,cours:null,desc:`d’identifier et de classer tous les types de lentilles ainsi que les différents types de produit d’entretien et de mettre en œuvre, en fonction du type de lentilles, une méthodologie à respecter pour la manipulation et l’entretien ;`},
  {code:`AA291.5`,num:5,ue:291,cours:null,desc:`d’identifier les différents types de verres (unifocal, progressif …), d’expliquer leurs avantages et inconvénients en fonction des besoins visuels du patient et de réaliser la mesure du type de verres choisi à l’aide du matériel approprié en respectant les normes de précision et la transcrire sur le dossier patient.`},
  {code:`AA285.1`,num:1,ue:285,cours:null,desc:`de mettre en œuvre une communication basée sur la compréhension de la relation patient partenaire ;`},
  {code:`AA285.2`,num:2,ue:285,cours:null,desc:`de réaliser une RCP avec ou sans défibrillateur.`},
  {code:`AA281.1`,num:1,ue:281,cours:null,desc:`d'expliquer le développement de diverses fonctions cérébrales ainsi que leurs atteintes chez l’enfant et chez l’adulte`},
  {code:`AA281.2`,num:2,ue:281,cours:null,desc:`d'expliquer les différentes étapes du développement psychologique chez l’être humain tout au long de la vie ainsi que l’impact des périodes critiques sur les étapes du développement`},
  {code:`AA281.3`,num:3,ue:281,cours:null,desc:`d'établir les relations entre l’état psychologique du patient et son état de santé`},
  {code:`AA283.1`,num:1,ue:283,cours:null,desc:`de situer la profession au regard des principes déontologiques et éthiques`},
  {code:`AA283.2`,num:2,ue:283,cours:null,desc:`d’identifier les limites de la responsabilité professionnelle`},
  {code:`AA283.3`,num:3,ue:283,cours:null,desc:`de mettre en œuvre une communication basée sur la compréhension de la relation soignant-patient`},
  {code:`AA284.1`,num:1,ue:284,cours:null,desc:`de décrire les principes de base de la gestion d’un dossier patient informatisé standard et de la prescription électronique`},
  {code:`AA284.2`,num:2,ue:284,cours:null,desc:`de caractériser le contexte institutionnel et légal des soins de santé et d’expliquer l’organisation générale des soins de santé en Belgique`},
  {code:`AA284.3`,num:3,ue:284,cours:null,desc:`de situer la profession au regard des fondements légaux, d’identifier les notions de responsabilité professionnelle civile et pénale et d'énoncer les droits et devoirs du professionnel en faisant référence aux principes de droit du travail`},
  {code:`AA284.4`,num:4,ue:284,cours:null,desc:`de relever les procédures d’intervention de la sécurité sociale applicables à la situation de soins de santé et d’analyser les forces et faiblesses d’un cadre professionnel afin d’améliorer la qualité de l’offre de soins`},
  {code:`AA303.1`,num:1,ue:303,cours:null,desc:`de corroborer son projet de formation au vu des différentes situations professionnelles rencontrées en stage en élaborant un rapport synthétique comportant`},
  {code:`AA303.2`,num:2,ue:303,cours:null,desc:`de synthétiser son projet professionnel en assurant la cohérence entre ses motivations personnelles, les exigences de la profession et de la formation, selon la structure suivante`},
  {code:`AA307.1`,num:1,ue:307,cours:null,desc:`d’effectuer une recherche sur la problématique choisie`},
  {code:`AA307.2`,num:2,ue:307,cours:null,desc:`de proposer et de justifier des pistes d’intervention en lien avec les apports théoriques et méthodologiques acquis et, s’il échoit, avec ses recherches personnelles`},
  {code:`AA307.3`,num:3,ue:307,cours:null,desc:`de présenter une approche intégrée des compétences de l’optométriste`},
  {code:`AA307.4`,num:4,ue:307,cours:null,desc:`de développer une réflexion critique, responsable et citoyenne`},
  {code:`AA307.5`,num:5,ue:307,cours:null,desc:`de réaliser une présentation structurée de son travail et de répondre d’une manière concise et claire aux questions en faisant la preuve qu’il maîtrise les concepts utilisés`},
  {code:`AA287.1`,num:1,ue:287,cours:null,desc:`de rédiger un dossier collectif rendant compte d’un projet en lien avec la profession`},
  {code:`AA288.1`,num:1,ue:288,cours:null,desc:`de réaliser des examens d’assistance en ophtalmologie et de préparer le matériel d’instrumentation ophtalmologique, d’expliquer les techniques (objectifs, conditions de réalisation, procédure) permettant de mettre en évidence et de mesurer les anomalies du système visuel`},
  {code:`AA288.2`,num:2,ue:288,cours:null,desc:`d’interpréter les résultats en comparaison aux normes afin de formuler un pré-diagnostic`},
  {code:`AA288.3`,num:3,ue:288,cours:null,desc:`de décrire les caractéristiques et le bon usage d’un collyre et de réaliser son administration`},
  {code:`AA288.4`,num:4,ue:288,cours:null,desc:`pour au moins deux médicaments ophtalmiques, d’expliquer leurs indications, leurs modes d’action, leurs caractéristiques, leurs effets attendus et leurs effets secondaires sur le système visuel`},
  {code:`AA299.1`,num:1,ue:299,cours:null,desc:`adapter le contenu et la structuration d’une anamnèse de base`},
  {code:`AA299.2`,num:2,ue:299,cours:null,desc:`réaliser l’anamnèse de base, l’examen visuel et l’exploration fonctionnelle du système visuel`},
  {code:`AA299.3`,num:3,ue:299,cours:null,desc:`tester et analyser la relation accommodation/convergence en vue d’une prise en charge optométrique`},
  {code:`AA299.4`,num:4,ue:299,cours:null,desc:`expliquer les modes d’interprétation des résultats en comparaison aux normes ou à un œil sain afin de formuler un pré-diagnostic`},
  {code:`AA300.1`,num:1,ue:300,cours:null,desc:`de procéder à l’étude complète de la vision : de réaliser une anamnèse, de reconnaître un éventuel état non physiologique, de choisir et de mettre en œuvre le testing adapté à la situation donnée, d’analyser les résultats, de proposer et de justifier une prise en charge adaptée, une planification thérapeutique et d’élaborer un rapport destiné à d’autres professionnels`},
  {code:`AA300.2`,num:2,ue:300,cours:null,desc:`d’expliquer au patient les problèmes visuels constatés, leur évolution et de lui donner des conseils en vue d’améliorer sa qualité de vision et son confort visuel`},
  {code:`AA300.3`,num:3,ue:300,cours:null,desc:`d’élaborer un plan d’aide dans les limites de la profession et de l’intégrer dans une prise en charge interdisciplinaire ou interprofessionnelle`},
  {code:`AA300.4`,num:4,ue:300,cours:null,desc:`de décrire les procédures des examens électrophysiologiques ainsi que leurs conditions de réalisation afin de différencier une situation normale et anormale`},
  {code:`AA300.5`,num:5,ue:300,cours:null,desc:`de décrire les principales atteintes en neuro-ophtalmologie ainsi que les troubles neuro-visuels`},
  {code:`AA300.6`,num:6,ue:300,cours:null,desc:`de caractériser les troubles oculo- vestibulaires et de proposer une prise en charge au sein d’une équipe interdisciplinaire et interprofessionnelle`},
  {code:`AA289.1`,num:1,ue:289,cours:null,desc:`d’établir les relations entre les dysfonctionnements du système visuel et les conditions qui engendrent l’état de malvoyance`},
  {code:`AA289.2`,num:2,ue:289,cours:null,desc:`d’expliquer les méthodes d’évaluation des capacités visuelles chez le déficient visuel`},
  {code:`AA289.3`,num:3,ue:289,cours:null,desc:`de déterminer le type de prise en charge en tenant compte des besoins et des attentes du patient et de justifier ses choix`},
  {code:`AA290.1`,num:1,ue:290,cours:null,desc:`de différencier et de classifier les mécanismes de fonctionnement de la motilité oculaire`},
  {code:`AA290.2`,num:2,ue:290,cours:null,desc:`de définir les éléments de la vision binoculaire`},
  {code:`AA290.3`,num:3,ue:290,cours:null,desc:`d’expliciter la mise en place de la vision binoculaire`},
  {code:`AA290.4`,num:4,ue:290,cours:null,desc:`d’identifier le type de strabisme concomitant`},
  {code:`AA301.1`,num:1,ue:301,cours:null,desc:`de mettre en œuvre les comportements opérationnels pour effectuer une adaptation en lentilles de contact souples (observations et mesures préalables, vérification des paramètres, choix et suivi des lentilles, validation et conseils au porteur) et de justifier de sa méthodologie`},
  {code:`AA301.2`,num:2,ue:301,cours:null,desc:`de communiquer les mesures requises pour assurer la conservation des lentilles et de déterminer le meilleur entretien en fonction du matériau et de l’ensemble des paramètres du porteur`},
  {code:`AA301.3`,num:3,ue:301,cours:null,desc:`d’analyser les données d’un porteur afin d’élaborer un dossier complet d’adaptation pouvant être utilisé par tout autre professionnel`},
  {code:`AA302.1`,num:1,ue:302,cours:null,desc:`d’élaborer un dossier d’adaptation complexe en lentilles de contact en tenant compte des attentes et des besoins du porteur (tout type de porteur amétrope ou non), des contraintes environnementales, visuelles et physiologiques, des lentilles disponibles sur le marché`},
  {code:`AA302.2`,num:2,ue:302,cours:null,desc:`de mettre en œuvre les comportements opérationnels pour procéder à l’adaptation d’un cas complexe en lentilles de contact`},
  {code:`AA302.3`,num:3,ue:302,cours:null,desc:`de justifier la procédure et les choix d’adaptation en se référant aux cadres théoriques et de rédiger un rapport destiné à tout autre professionnel`},
  {code:`AA302.4`,num:4,ue:302,cours:null,desc:`d’estimer le coût des lentilles, le coût de leur entretien et de leur adaptation selon la proposition adoptée, en tenant compte de l'intervention des assurances et de la sécurité sociale`},
  {code:`AA292.1`,num:1,ue:292,cours:null,desc:`de décrire les caractéristiques et le fonctionnement d’au moins deux systèmes parmi les suivants : épithélial, conjonctif, immunitaire (normal et dérèglement), musculaire, circulatoire, endocrinien, vestibulo-oculaire, squelettique`},
  {code:`AA292.2`,num:2,ue:292,cours:null,desc:`de décrire la structure et le fonctionnement des différentes parties du système nerveux, d’en décrire les pathologies ou dysfonctionnements les plus courants`},
  {code:`AA293.1`,num:1,ue:293,cours:null,desc:`d’identifier les composants du système visuel et d’expliciter la structure et les spécificités d’au moins deux éléments relatifs au globe oculaire, à ses annexes et aux voies optiques`},
  {code:`AA293.2`,num:2,ue:293,cours:null,desc:`de décrire les rôles, la composition chimique et physique, les métabolismes, les modes de fonctionnement et les effets régulateurs d’au moins deux constituants de l’œil et de ses annexes et d’expliciter la réception et la transmission du message visuel le long des voies optiques ainsi que son intégration au niveau du cerveau`},
  {code:`AA294.1`,num:1,ue:294,cours:null,desc:`de décrire les causes, les symptômes, les dysfonctionnements, les évolutions et les modalités de prise en charge d’une pathologie générale courante et ses complications au niveau ophtalmologique`},
  {code:`AA294.2`,num:2,ue:294,cours:null,desc:`d’expliquer, la circulation d’un médicament dans le corps humain en s’appuyant sur les principes et les lois de la pharmacologie et pour au moins deux médicaments ophtalmiques, d’expliquer leurs indications, modes d’action, caractéristiques, effets sur le système visuel et effets secondaires`},
  {code:`AA295.1`,num:1,ue:295,cours:null,desc:`d’expliquer les techniques d’examen à mettre en œuvre`},
  {code:`AA295.2`,num:2,ue:295,cours:null,desc:`d’identifier et de décrire la pathologie concernée`},
  {code:`AA295.3`,num:3,ue:295,cours:null,desc:`d’établir les relations entre les dysfonctionnements, les causes, les symptômes, les évolutions et les traitements`},
  {code:`AA295.4`,num:4,ue:295,cours:null,desc:`de justifier les traitements utilisés en tenant compte des limites déontologiques de la profession`},
  {code:`AA304.1`,num:1,ue:304,cours:null,desc:`d’élaborer un rapport technique comportant : la description des techniques d’assistance en instrumentation ophtalmologique observées et pratiquées, la présentation d’un cas clinique observé en assistance en instrumentation ophtalmologique, l’utilisation des matériaux dans un exemple de processus de développement durable, une réflexion critique et argumentée des interventions réalisées pendant le stage`},
  {code:`AA305.1`,num:1,ue:305,cours:null,desc:`d’élaborer un rapport technique comportant : la description des méthodes d’exploration visuelle et des pratiques en contactologie observées et pratiquées,  la présentation d’un cas clinique observé en exploration visuelle et en contactologie, une réflexion critique et argumentée des interventions réalisées pendant le stage`},
  {code:`AA306.1`,num:1,ue:306,cours:null,desc:`de respecter les termes de la convention de stage`},
  {code:`AA306.2`,num:2,ue:306,cours:null,desc:`de rédiger et de présenter oralement un rapport de stage personnel, critique et argumenté`},
  {code:`AA306.3`,num:3,ue:306,cours:null,desc:`de montrer sa propre maitrise d'analyse et de recherche de solutions de compensations et de corrections pertinentes dans les différentes sphères d’activités de l’optométrie en tenant compte des caractéristiques du patient et de son milieu`},
  {code:`AA297.1`,num:1,ue:297,cours:null,desc:`de résoudre des problèmes complexes portant sur des situations relatives à des systèmes optiques en appliquant les règles de calcul, les formules et les lois pertinentes sur le plan opératoire et de valider les résultats obtenus par une méthode de contrôle`},
  {code:`AA297.2`,num:2,ue:297,cours:null,desc:`de décrire et de proposer un instrument d’optique, de justifier son choix en fonction de ses caractéristiques et son mode d’utilisation, de calculer les grandeurs d’images, les champs, le pouvoir séparateur et la clarté`},
  {code:`AA297.3`,num:3,ue:297,cours:null,desc:`de proposer des solutions optiques en fonction des besoins visuels du patient en suivant l’évolution technologique`},
  {code:`AA298.1`,num:1,ue:298,cours:null,desc:`d’adapter le contenu et la structuration d’une anamnèse de base`},
  {code:`AA298.2`,num:2,ue:298,cours:null,desc:`de réaliser l’anamnèse de base, l’examen visuel et l’exploration fonctionnelle du système visuel`},
  {code:`AA298.3`,num:3,ue:298,cours:null,desc:`de tester et d’analyser la relation accommodation/convergence en vue d’une prise en charge optométrique`},
  {code:`AA298.4`,num:4,ue:298,cours:null,desc:`d’expliquer les modes d’interprétation des résultats en comparaison aux normes ou à un œil sain afin de formuler un pré-diagnostic`},
  {code:`AA296.1`,num:1,ue:296,cours:null,desc:`de présenter une démarche de recherche qui intègre : la méthodologie de l’Evidence-based medicine et Evidence-based practice (EBM-EBP), une recherche documentaire (en français et/ou en anglais), les objectifs et les hypothèses de travail, les données à recueillir et les modalités de recueil, le traitement des données et l'interprétation des statistiques, les références bibliographiques, l'évaluation rigoureuse et critique des sources et résultats`},
  {code:`AA65.1`,num:1,ue:65,cours:null,desc:`de définir et d’illustrer les concepts essentiels relatifs aux différents champs de la psychomotricité`},
  {code:`AA65.2`,num:2,ue:65,cours:null,desc:`d’exprimer ses perceptions émotionnelles, mentales, sensorielles basées sur une description de faits précis issus d’activités corporelles`},
  {code:`AA65.3`,num:3,ue:65,cours:null,desc:`de poser les prémices de son projet de formation en assurant la cohérence entre ses motivations personnelles et les exigences de la formation`},
  {code:`AA66.1`,num:1,ue:66,cours:null,desc:`de définir et d’utiliser les concepts et processus essentiels relatifs aux différents champs de la psychologie et de la pédagogie`},
  {code:`AA66.2`,num:2,ue:66,cours:null,desc:`d’analyser une situation professionnelle en utilisant les concepts et les processus relatifs aux différents champs de la psychologie et de la pédagogie`},
  {code:`AA66.3`,num:3,ue:66,cours:null,desc:`"au départ de situations susceptibles d’être rencontrées dans un espace : d’appliquer les principes de base de la relation d’aide et de la communication interpersonnelle professionnel; d’analyser les facteurs qui ont influencé les interactions entre les membres d’un groupe"`},
  {code:`AA67.1`,num:1,ue:67,cours:null,desc:`de définir, d’utiliser et d’illustrer différents concepts et notions de base relatifs aux domaines des sciences fondamentales et biomédicales`},
  {code:`AA67.2`,num:2,ue:67,cours:null,desc:`d’analyser une situation professionnelle donnée en établissant des liens entre différents domaines et concepts relevant des sciences fondamentales et biomédicales`},
  {code:`AA67.3`,num:3,ue:67,cours:null,desc:`de relever les éléments relatifs à la santé publique et/ou à la promotion de la santé dans une situation professionnelle donnée`},
  {code:`AA68.1`,num:1,ue:68,cours:null,desc:`d’identifier différentes pathologies générales et spéciales et d’en expliciter les caractéristiques`},
  {code:`AA68.2`,num:2,ue:68,cours:null,desc:`d'appliquer des concepts de la biomécanique à la description et à l'analyse de différents mouvements du corps humain`},
  {code:`AA69.1`,num:1,ue:69,cours:null,desc:`de rédiger un écrit professionnel adapté à une situation de travail donnée et d’en justifier la forme et le contenu en fonction du contexte, des objectifs poursuivis et de la destination`},
  {code:`AA69.2`,num:2,ue:69,cours:null,desc:`à partir d’une problématique donnée, de proposer une méthodologie de recherche qui intègre les points suivants : objectifs, hypothèses de travail, données à recueillir, modalités de recueil et référents théoriques à mobiliser`},
  {code:`AA69.3`,num:3,ue:69,cours:null,desc:`d'analyser une situation professionnelle en intégrant les caractéristiques organisationnelles et les modalités du travail pluridisciplinaire concomitantes à cette situation`},
  {code:`AA70.1`,num:1,ue:70,cours:null,desc:`d’observer la dynamique psychomotrice d’un sujet et d’établir son bilan psychomoteur en utilisant les tests et outils appropriés`},
  {code:`AA70.2`,num:2,ue:70,cours:null,desc:`d’élaborer une intervention psychomotrice`},
  {code:`AA70.3`,num:3,ue:70,cours:null,desc:`de repérer et de développer les différents aspects du rôle de psychomotricien`},
  {code:`AA71.1`,num:1,ue:71,cours:null,desc:`à partir d’une situation concrète, d’élaborer et de justifier une intervention en soin psychomoteur et en thérapie psychomotrice en fonction d’un public déterminé`},
  {code:`AA71.2`,num:2,ue:71,cours:null,desc:`d’évaluer sa pratique et d’analyser sa technicité en thérapie psychomotrice`},
  {code:`AA71.3`,num:3,ue:71,cours:null,desc:`de communiquer sur les éléments de son intervention de manière adaptée`},
  {code:`AA72.1`,num:1,ue:72,cours:null,desc:`de définir et d’illustrer des concepts et processus relatifs à la psychomotricité, au développement psychomoteur, à la neurologie, à la psychologie clinique, à la sociologie et à la philosophie`},
  {code:`AA73.1`,num:1,ue:73,cours:null,desc:`d’agir en tant qu’initiateur et récepteur de relations à travers le dialogue tonico-émotionnel`},
  {code:`AA73.2`,num:2,ue:73,cours:null,desc:`d’exprimer ses perceptions émotionnelles, sensorielles et sensori-motrices, basées sur une`},
  {code:`AA73.3`,num:3,ue:73,cours:null,desc:`de décrire les processus relationnels issus de son expérience vécue au cours des activité`},
  {code:`AA73.4`,num:4,ue:73,cours:null,desc:`de dégager, à partir des situations vécues au cours des activités d’enseignement, des éléments constitutifs de son profil psychomoteur`},
  {code:`AA74.1`,num:1,ue:74,cours:null,desc:`d’élaborer une intervention thérapeutique intégrant des éléments de psychopathologie, de troubles psychomoteurs ou de médication éventuelle`},
  {code:`AA74.2`,num:2,ue:74,cours:null,desc:`de poser une réflexion éthique et s’il échoit, d’établir des liens avec la législation en vigueur`},
  {code:`AA75.1`,num:1,ue:75,cours:null,desc:`de se mettre en jeu corporellement dans une intervention psychomotrice, notamment comme référent d’identification et comme partenaire symbolique`},
  {code:`AA75.2`,num:2,ue:75,cours:null,desc:`de proposer et de justifier des techniques adaptées dans la perspective d’une situation d’intervention psychomotrice, y compris thérapeutique`},
  {code:`AA75.3`,num:3,ue:75,cours:null,desc:`d’identifier ses forces et ses faiblesses dans l’application de la technicité psychomotrice`},
  {code:`AA76.1`,num:1,ue:76,cours:null,desc:`d’élaborer un rapport synthétique comportant : une description des tâches réalisées ainsi que de leur contexte institutionnel et relationnel (entreprise ou organisme), une réflexion critique et argumentée de ce qui a pu être fait.`},
  {code:`AA77.1`,num:1,ue:77,cours:null,desc:`de décrire une ou plusieurs situations d’intervention psychomotrice en ce compris le(s) contexte(s) de travail et les caractéristiques du public cible`},
  {code:`AA77.2`,num:2,ue:77,cours:null,desc:`de présenter une observation rigoureuse en se fondant sur des indices corporels`},
  {code:`AA77.3`,num:3,ue:77,cours:null,desc:`d’identifier les acquis de son expérience de stage`},
  {code:`AA78.1`,num:1,ue:78,cours:null,desc:`de décrire et d’analyser des séquences d’intervention psychomotrice`},
  {code:`AA78.2`,num:2,ue:78,cours:null,desc:`d’analyser sa relation au bénéficiaire, à son entourage et à l’équipe`},
  {code:`AA78.3`,num:3,ue:78,cours:null,desc:`de décrire et d’analyser le processus relationnel engagé dans son intervention comme psychomotricien`},
  {code:`AA78.4`,num:4,ue:78,cours:null,desc:`d’identifier et d’évaluer les acquis de son expérience de stage en vue de construire son identité professionnelle (limites et ressources) en tenant compte des spécificités du(des) bénéficiaire(s)`},
  {code:`AA79.1`,num:1,ue:79,cours:null,desc:`de concevoir, réaliser et évaluer des interventions psychomotrices qui intègrent : les caractéristiques du public (développement psychomoteur,  des techniques d’intervention psychomotrice, potentialités, fragilités, ...),  des techniques d’intervention psychomotrice,  les conditions relationnelles, spatiales et temporelles, ...`},
  {code:`AA79.2`,num:2,ue:79,cours:null,desc:`d’identifier et d’évaluer les acquis de son expérience d’activités professionnelles de formation en vue de l’aider à construire son identité professionnelle (limites et ressources)`},
  {code:`AA79.3`,num:3,ue:79,cours:null,desc:`de relever et de décrire en quoi les activités professionnelles de formation lui ont permis d’appréhender les différentes facettes du métier de psychomotricien`},
  {code:`AA79.4`,num:4,ue:79,cours:null,desc:`de décrire, d’analyser et d’évaluer son degré de maîtrise psycho-corporelle atteint`},
  {code:`AA80.1`,num:1,ue:80,cours:null,desc:`d’effectuer une recherche documentaire sur la problématique choisie`},
  {code:`AA80.2`,num:2,ue:80,cours:null,desc:`de proposer et de justifier des pistes d’intervention en lien avec les apports théoriques et méthodologiques acquis et, s’il échoit, avec ses recherches personnelles`},
  {code:`AA80.3`,num:3,ue:80,cours:null,desc:`d’intégrer différentes dimensions de l’intervention psychomotrice : diagnostic, éducation- prévention, thérapie, déontologie, réflexivité, pluridisciplinarité...`},
  {code:`AA80.4`,num:4,ue:80,cours:null,desc:`de développer une réflexion critique et éthique`},
  {code:`AA80.5`,num:5,ue:80,cours:null,desc:`de réaliser une présentation structurée de son travail et de répondre d’une manière concise et claire aux questions en faisant la preuve qu’il maîtrise les concepts utilisés`},
  {code:`AA261.1`,num:1,ue:261,cours:null,desc:`de corroborer son projet de formation au vu des différentes situations professionnelles rencontrées en stage en élaborant un rapport synthétique comportant`},
  {code:`AA261.2`,num:2,ue:261,cours:null,desc:`de synthétiser son projet professionnel en assurant la cohérence entre ses motivations personnelles, les exigences de la profession et de la formation, selon la structure suivante`},
  {code:`AA246.1`,num:1,ue:246,cours:null,desc:`de décrire la structure, le fonctionnement et les mécanismes de reproduction d’une cellule animale`},
  {code:`AA246.2`,num:2,ue:246,cours:null,desc:`de citer les constantes biologiques courantes et de décrire leurs champs d’application`},
  {code:`AA246.3`,num:3,ue:246,cours:null,desc:`d’analyser une notice de produits de contrastes et d’expliquer l’osmolarité des produits de contraste`},
  {code:`AA246.4`,num:4,ue:246,cours:null,desc:`d’analyser une gazométrie veineuse et artérielle`},
  {code:`AA247.1`,num:1,ue:247,cours:null,desc:`dans des cas concrets de traitements en imagerie médicale, de déterminer les produits adaptés aux images ou aux traitements à effectuer en utilisant les connaissances théoriques en pharmacologie vues au cours`},
  {code:`AA247.2`,num:2,ue:247,cours:null,desc:`d’identifier les interactions possibles entre les différents produits et leurs conséquences sur le corps humain`},
  {code:`AA247.3`,num:3,ue:247,cours:null,desc:`d’expliciter la mise à jour des stocks en produits et matériels nécessaires aux examens d’imagerie médicale`},
  {code:`AA248.1`,num:1,ue:248,cours:null,desc:`de décrire les principes fondamentaux de physique applicables à l’imagerie médicale`},
  {code:`AA248.2`,num:2,ue:248,cours:null,desc:`d’expliquer la formation des rayonnements ionisants et non ionisants et leurs interactions avec la matière`},
  {code:`AA248.3`,num:3,ue:248,cours:null,desc:`d’expliquer la formation d’une onde mécanique et les interactions de ces ondes avec la matière`},
  {code:`AA248.4`,num:4,ue:248,cours:null,desc:`de décrire les différents détecteurs utilisés en imagerie médicale (radiologie standard, scanner …)`},
  {code:`AA249.1`,num:1,ue:249,cours:null,desc:`d’expliquer la manière de visualiser une image en nuances de gris ainsi que les notions de fenêtre et de centre`},
  {code:`AA249.2`,num:2,ue:249,cours:null,desc:`de développer le traitement et le parcours de l’image numérique jusqu’au post-processing`},
  {code:`AA249.3`,num:3,ue:249,cours:null,desc:`de décrire les fonctions des différents systèmes informatiques et systèmes de fichiers (RIS, PACS, DICOM …)`},
  {code:`AA249.4`,num:4,ue:249,cours:null,desc:`de justifier l’importance de la sécurité des données médicales des patients`},
  {code:`AA250.1`,num:1,ue:250,cours:null,desc:`d’expliciter les différentes techniques d’acquisition et de formation de l’image`},
  {code:`AA250.2`,num:2,ue:250,cours:null,desc:`de synthétiser et d’analyser les informations collectées nécessaires à la réalisation de l’examen demandé par le prescripteur`},
  {code:`AA250.3`,num:3,ue:250,cours:null,desc:`de justifier la préparation et le positionnement du patient afin d’obtenir les images demandées par le prescripteur`},
  {code:`AA252.1`,num:1,ue:252,cours:null,desc:`d’informer le patient et les différents partenaires sur les risques des rayons ionisants`},
  {code:`AA252.2`,num:2,ue:252,cours:null,desc:`d’expliquer et de justifier les mesures de précaution qui concernent la radioprotection`},
  {code:`AA253.1`,num:1,ue:253,cours:null,desc:`d’expliquer le rôle et les responsabilités de chaque intervenant`},
  {code:`AA253.2`,num:2,ue:253,cours:null,desc:`d’expliquer l’acquisition des images nécessaires à la planification du traitement, le repérage de la zone à traiter et la simulation du traitement à réaliser par radiothérapie`},
  {code:`AA253.3`,num:3,ue:253,cours:null,desc:`d’expliciter et de justifier des techniques de positionnement du patient`},
  {code:`AA253.4`,num:4,ue:253,cours:null,desc:`de détailler la préparation, la surveillance et le suivi du patient tout au long de la procédure de traitement`},
  {code:`AA253.5`,num:5,ue:253,cours:null,desc:`de vérifier la dosimétrie proposée`},
  {code:`AA253.6`,num:6,ue:253,cours:null,desc:`de développer les compétences nécessaires en termes de suivi psychologique du patient`},
  {code:`AA254.1`,num:1,ue:254,cours:null,desc:`d’expliquer les caractéristiques et le fonctionnement d’au moins deux systèmes du corps humain parmi les suivants : épithélial, conjonctif, digestif, respiratoire, locomoteur, cardio-vasculaire, endocrinien, immunitaire/lymphatique, nerveux, musculo-squelettique, uro-génital et tégumentaire`},
  {code:`AA254.2`,num:2,ue:254,cours:null,desc:`d'énoncer, de définir et de décrire, en termes scientifiques, les symptômes et les facteurs étiologiques les plus courants ainsi que les éléments fondamentaux du processus physiopathologique`},
  {code:`AA254.3`,num:3,ue:254,cours:null,desc:`d’expliquer, en utilisant le vocabulaire spécifique, les différents mécanismes participant à la défense de l’organisme humain contre les infections ainsi que leurs interactions, les troubles associés et leurs implications en matière de diagnostic`},
  {code:`AA254.4`,num:4,ue:254,cours:null,desc:`d’expliquer l’utilité de la récolte de données en imagerie médicale`},
  {code:`AA254.5`,num:5,ue:254,cours:null,desc:`de décrire les soins liés à la peau (pansement simple, soin de plaie simple et complexe, pansement compressif …)`},
  {code:`AA254.6`,num:6,ue:254,cours:null,desc:`d’expliciter les notions de base de l’hygiène hospitalière et de justifier les mesures de prévention des infections à mettre en place`},
  {code:`AA255.1`,num:1,ue:255,cours:null,desc:`de décrire précisément un organe depuis chaque modalité d’examen spécifique`},
  {code:`AA255.2`,num:2,ue:255,cours:null,desc:`de repérer et de justifier les signes des pathologies`},
  {code:`AA255.3`,num:3,ue:255,cours:null,desc:`de justifier les techniques de soins appliquées aux différentes modalités d’examens spécifiques et de sélectionner la technique la plus adaptée et d’en justifier le choix`},
  {code:`AA255.4`,num:4,ue:255,cours:null,desc:`d’expliciter et de simuler un prélèvement sanguin (gazométrie, matériel de prélèvement, perfusion, sites de ponction …)`},
  {code:`AA255.5`,num:5,ue:255,cours:null,desc:`d’observer sur moniteur le contrôle des fonctions cardio-vasculaire, respiratoire et neurologique et d’interpréter les paramètres observés`},
  {code:`AA257.1`,num:1,ue:257,cours:null,desc:`au départ d’un support de communication verbale et professionnelle, d’exposer les éléments essentiels exploitables dans le cadre de son travail`},
  {code:`AA257.2`,num:2,ue:257,cours:null,desc:`d’adapter, dans un cas donné de prise en charge d’un patient, sa communication verbale et non verbale à la situation`},
  {code:`AA257.3`,num:3,ue:257,cours:null,desc:`de situer la profession de technologue en imagerie médicale, au regard des fondements légaux, des principes déontologiques, de l’éthique professionnelle et des aspects responsables et citoyens`},
  {code:`AA257.4`,num:4,ue:257,cours:null,desc:`d’identifier les notions de responsabilité professionnelle civile et pénale`},
  {code:`AA257.5`,num:5,ue:257,cours:null,desc:`d'énoncer les droits et devoirs du technologue en imagerie médicale en faisant référence aux principes de droit du travail`},
  {code:`AA258.1`,num:1,ue:258,cours:null,desc:`d’effectuer une recherche bibliographique sur un sujet et d’analyser sa pertinence`},
  {code:`AA262.1`,num:1,ue:262,cours:null,desc:`de respecter les termes de la convention de stage`},
  {code:`AA262.2`,num:2,ue:262,cours:null,desc:`de concevoir, de réaliser et d’évaluer la pertinence des examens en imagerie médicale pour les activités professionnelles suivantes`},
  {code:`AA262.3`,num:3,ue:262,cours:null,desc:`d’adapter ses comportements dans un environnement de soins et dans des milieux multiculturels`},
  {code:`AA262.4`,num:4,ue:262,cours:null,desc:`d’accompagner des parents et /ou d’autres collaborateurs directs dans une prise en charge pluridisciplinaire …`},
  {code:`AA262.5`,num:5,ue:262,cours:null,desc:`de rédiger un rapport de stage personnel, critique et argumenté mettant en évidence`},
  {code:`AA258.2`,num:2,ue:258,cours:null,desc:`de synthétiser les informations reprises dans au moins trois sources scientifiques différentes et d’en produire une synthèse personnelle`},
  {code:`AA258.3`,num:3,ue:258,cours:null,desc:`d’indiquer, dans le respect des normes de référencement bibliographique, les sources utilisées pour la réalisation du travail`},
  {code:`AA259.1`,num:1,ue:259,cours:null,desc:`de présenter une démarche de recherche qui intègre : une recherche documentaire en français et en anglais, les objectifs, les hypothèses de travail, les données à recueillir, les modalités de recueil, le traitement des données et les référents théoriques mobilisés`},
  {code:`AA260.1`,num:1,ue:260,cours:null,desc:`de développer des outils de contrôle de qualité en imagerie médicale et de contrôle de doses d’exposition aux rayonnements ionisants`},
  {code:`AA260.2`,num:2,ue:260,cours:null,desc:`de justifier l’application, au sein d’un service d’imagerie médicale, des procédures de contrôle de qualité et de contrôle de doses`},
  {code:`AA260.3`,num:3,ue:260,cours:null,desc:`d’expliciter les éléments clés de la législation relative au contrôle de qualité d’un service d’imagerie médicale`},
  {code:`AA266.1`,num:1,ue:266,cours:null,desc:`d’analyser une grille critériée`},
  {code:`AA266.2`,num:2,ue:266,cours:null,desc:`d’en discuter et d’en débattre de manière argumentée`},
  {code:`AA267.1`,num:1,ue:267,cours:null,desc:`d’analyser un projet individuel d’apprentissage (issu du spécialisé ou de l’ordinaire)`},
  {code:`AA267.2`,num:2,ue:267,cours:null,desc:`le cas échéant, d’analyser le dossier d’apprentissage d’un élève`},
  {code:`AA267.3`,num:3,ue:267,cours:null,desc:`d’en discuter et d’en débattre de manière argumentée`},
  {code:`AA268.1`,num:1,ue:268,cours:null,desc:`d’analyser la séquence d’apprentissage à l’aide d’une grille d’observation et/ou d’évaluation`},
  {code:`AA268.2`,num:2,ue:268,cours:null,desc:`de présenter un feed-back au chargé de cours, notamment des conseils`},
  {code:`AA269.1`,num:1,ue:269,cours:null,desc:`sur base de projet pédagogique de l’école, de construire un outil d’observation et d’évaluation d’une séquence d’apprentissage`},
  {code:`AA270.1`,num:1,ue:270,cours:null,desc:`d’analyser la séquence d’apprentissage à l’aide d’une grille d’observation et/ou d’évaluation`},
  {code:`AA270.2`,num:2,ue:270,cours:null,desc:`de présenter un feed-back à l’enseignant, notamment des conseils`},
  {code:`AA271.1`,num:1,ue:271,cours:null,desc:`d’analyser la séquence d’apprentissage à l’aide d’une grille d’observation et/ou d’évaluation`},
  {code:`AA271.2`,num:2,ue:271,cours:null,desc:`de présenter un feed-back à l’enseignant, notamment des conseils`},
  {code:`AA272.1`,num:1,ue:272,cours:null,desc:`d’analyser la séquence d’apprentissage à l’aide d’une grille d’observation et/ou d’évaluation`},
  {code:`AA272.2`,num:2,ue:272,cours:null,desc:`de présenter un feed-back à l’enseignant, notamment des conseils`},
  {code:`AA273.1`,num:1,ue:273,cours:null,desc:`la mise en place des pratiques démocratiques de citoyenneté responsable au sein de l’école`},
  {code:`AA273.2`,num:2,ue:273,cours:null,desc:`la promotion de la mixité sociale au sein de l’école`},
  {code:`AA274.1`,num:1,ue:274,cours:null,desc:`de présenter de manière structurée une analyse de situation professionnelle vécue et de proposer une politique pédagogique, en lien avec son  projet d’école`},
  {code:`AA274.2`,num:2,ue:274,cours:null,desc:`d’exposer lors de l’entretien, les liens pertinents avec le projet éducatif de la FELSI`},
  {code:`AA274.3`,num:3,ue:274,cours:null,desc:`d’en discuter et d’en débattre de manière argumentée`},
  {code:`AA275.1`,num:1,ue:275,cours:null,desc:`sur base du projet pédagogique et artistique de l’école, de proposer un plan d’actions`},
  {code:`AA275.2`,num:2,ue:275,cours:null,desc:`d’exposer lors de l’entretien, les liens pertinents avec sa mission pédagogique et éducative`},
  {code:`AA275.3`,num:3,ue:275,cours:null,desc:`d’en discuter et d’en débattre de manière argumentée`},
  {code:`AA276.1`,num:1,ue:276,cours:null,desc:`sur base du projet pédagogique de l’école et d’un plan d’accompagnement des étudiants, de proposer un plan d’actions pour atteindre les objectifs`},
  {code:`AA276.2`,num:2,ue:276,cours:null,desc:`d’exposer lors de l’entretien, les liens pertinents avec sa mission pédagogique et éducative`},
  {code:`AA276.3`,num:3,ue:276,cours:null,desc:`d’en discuter et d’en débattre de manière argumentée`},
  {code:`AA277.1`,num:1,ue:277,cours:null,desc:`d’analyser une grille critériée`},
  {code:`AA277.2`,num:2,ue:277,cours:null,desc:`d’en discuter et d’en débattre de manière argumentée`},
  {code:`AA278.1`,num:1,ue:278,cours:null,desc:`sur base du projet pédagogique de l’école, de proposer un plan d’actions`},
  {code:`AA278.2`,num:2,ue:278,cours:null,desc:`d’exposer lors de l’entretien, les liens pertinents avec sa mission pédagogique et éducative`},
  {code:`AA278.3`,num:3,ue:278,cours:null,desc:`d’en discuter et d’en débattre de manière argumentée`},
  {code:`AA219.1`,num:1,ue:219,cours:null,desc:`de réaliser un bilan global de la situation et de mettre en œuvre les règles essentielles d’intervention`},
  {code:`AA219.2`,num:2,ue:219,cours:null,desc:`d’effectuer la prise en charge de la victime dans le cadre des premiers secours, selon les normes en vigueur`},
  {code:`AA220.1`,num:1,ue:220,cours:null,desc:`de citer et d’expliciter les éléments et les règles essentiels liés à l’usage, à la vérification du fonctionnement d’une ambulance, à son contenu, à sa sécurité avant et après la prise en charge`},
  {code:`AA220.2`,num:2,ue:220,cours:null,desc:`de citer les informations pertinentes à recueillir et à transmettre à la centrale d’appel`},
  {code:`AA220.3`,num:3,ue:220,cours:null,desc:`de définir et de caractériser une communication efficace et ses moyens techniques lors d’un transport en ambulance`},
  {code:`AA220.4`,num:4,ue:220,cours:null,desc:`de décrire des troubles liés aux systèmes neurologique, respiratoire, circulatoire et locomoteur ainsi que les éléments essentiels des mécanismes anatomophysiologiques y afférents en vue de réaliser le transport sécuritaire du patient`},
  {code:`AA220.5`,num:5,ue:220,cours:null,desc:`de caractériser une situation nécessitant l’administration d’oxygène médical`},
  {code:`AA220.6`,num:6,ue:220,cours:null,desc:`d’identifier et de caractériser les principes nécessaires pour assurer`},
  {code:`AA221.1`,num:1,ue:221,cours:null,desc:`au départ d’un support de communication verbale et professionnelle, d’extraire et de reformuler oralement les éléments essentiels exploitables dans le cadre de son travail`},
  {code:`AA221.2`,num:2,ue:221,cours:null,desc:`au départ d’un support de communication écrite et professionnelle, de résumer par écrit le contenu essentiel exploitable dans le cadre son travail`},
  {code:`AA221.3`,num:3,ue:221,cours:null,desc:`lors d’une prise en charge d’un patient, d’adapter sa communication verbale et non verbale à la situation.`},
  {code:`AA222.1`,num:1,ue:222,cours:null,desc:`de réaliser un bilan de la situation du patient`},
  {code:`AA222.2`,num:2,ue:222,cours:null,desc:`de lever, de soulever, de positionner, de déplacer, d’immobiliser adéquatement le patient selon son état en tenant compte des accessoires et des techniques disponibles, dans le respect des principes d’ergonomie et de manutention afin de garantir sa sécurité`},
  {code:`AA222.3`,num:3,ue:222,cours:null,desc:`d’adapter son comportement vis-à-vis du patient, de sa famille et/ou de son entourage`},
  {code:`AA222.4`,num:4,ue:222,cours:null,desc:`de prendre en compte les aspects déontologiques`},
  {code:`AA222.5`,num:5,ue:222,cours:null,desc:`de surveiller le patient en fonction de son problème de santé`},
  {code:`AA222.6`,num:6,ue:222,cours:null,desc:`de transporter le patient vers sa destination en respectant les règles de sécurité, d’hygiène et de prévention des infections`},
  {code:`AA222.7`,num:7,ue:222,cours:null,desc:`d’identifier la dégradation de l’état de santé du patient et d’analyser le risque encouru par celui-ci afin de pouvoir juger de la nécessité d’une assistance selon son état`},
  {code:`AA222.8`,num:8,ue:222,cours:null,desc:`d’appeler les renforts/secours spécialisés`},
  {code:`AA222.9`,num:9,ue:222,cours:null,desc:`d’assurer le maintien des fonctions vitales en l’attente des secours spécialisés`},
  {code:`AA222.10`,num:10,ue:222,cours:null,desc:`de continuer à traiter le patient par oxygène médical`},
  {code:`AA222.11`,num:11,ue:222,cours:null,desc:`de transmettre, dans le respect des procédures, les informations relatives au patient et à la mission`},
  {code:`AA223.1`,num:1,ue:223,cours:null,desc:`de rendre compte dans un rapport écrit de ses observations et questionnements au terme de la prise en charge de patients`},
  {code:`AA223.2`,num:2,ue:223,cours:null,desc:`de décrire et de justifier une démarche de prise en charge professionnelle, comme ambulancier de transport non urgent de patients, tant au niveau du patient que de son transport`},
  {code:`AA223.3`,num:3,ue:223,cours:null,desc:`de poser les gestes techniques adaptés aux situations rencontrées`},
  {code:`AA223.4`,num:4,ue:223,cours:null,desc:`d’adopter des attitudes de travail en équipe d’ambulanciers de transport non urgent de patients et de collaborer avec des équipes multidisciplinaires au profit d’une prise en charge efficace`},
  {code:`AA223.5`,num:5,ue:223,cours:null,desc:`de questionner les prises en charge auxquelles il a participé sur le plan des gestes professionnels, de la collaboration en équipe, de la communication professionnelle, de sa relation avec le patient`},
  {code:`AA224.1`,num:1,ue:224,cours:null,desc:`de décrire une situation interpellante de transport non urgent d’un patient`},
  {code:`AA224.2`,num:2,ue:224,cours:null,desc:`d’analyser dans cette situation la prise en charge du patient en y identifiant les éléments significatifs liés à l’exercice de la profession`},
  {code:`AA224.3`,num:3,ue:224,cours:null,desc:`de mener une réflexion professionnelle rigoureuse, intégrant les différentes dimensions et aspects déontologiques du métier, soucieuse d'améliorer la qualité de sa prise en charge et de développer son identité professionnelle`},
  {code:`AA224.4`,num:4,ue:224,cours:null,desc:`de synthétiser son analyse et sa réflexion dans le cadre d’un travail écrit`},
  {code:`AA224.5`,num:5,ue:224,cours:null,desc:`de défendre oralement son analyse et sa réflexion`},
  {code:`AA225.1`,num:1,ue:225,cours:null,desc:`lever, soulever et positionner correctement le patient en fonction de son état de santé en vue du transport, y compris son déplacement avec ou sans accessoires`},
  {code:`AA225.2`,num:2,ue:225,cours:null,desc:`immobiliser le patient afin de garantir sa sécurité pendant le transport`},
  {code:`AA225.3`,num:3,ue:225,cours:null,desc:`veiller à la sécurité physique du patient`},
  {code:`AA225.4`,num:4,ue:225,cours:null,desc:`surveiller l'état du patient`},
  {code:`AA225.5`,num:5,ue:225,cours:null,desc:`continuer à traiter le patient par oxygène`},
  {code:`AA226.1`,num:1,ue:226,cours:null,desc:`au départ d'un support de communication verbale et professionnelle, d'extraire et de reformuler oralement les éléments essentiels exploitables dans le cadre de son travail`},
  {code:`AA226.2`,num:2,ue:226,cours:null,desc:`au départ d'un support de communication écrite et professionnelle, de résumer par écrit le contenu essentiel exploitable dans le cadre de son travail`},
  {code:`AA226.3`,num:3,ue:226,cours:null,desc:`lors d'une prise en charge d'un patient, d'adapter sa communication verbale et non verbale à la situation`},
  {code:`AA226.4`,num:4,ue:226,cours:null,desc:`de lever, de soulever, de positionner, d'immobiliser adéquatement le patient selon son état en tenant compte des accessoires et des techniques disponibles, dans le respect des principes d'ergonomie et de manutention afin de garantir sa sécurité`},
  {code:`AA226.5`,num:5,ue:226,cours:null,desc:`d'adapter son comportement vis-à-vis du patient, de sa famille et/ou de son entourage`},
  {code:`AA226.6`,num:6,ue:226,cours:null,desc:`de prendre en compte les aspects déontologiques`},
  {code:`AA226.7`,num:7,ue:226,cours:null,desc:`d'identifier la dégradation de l'état de santé du patient et d'analyser le risque encouru par celui-ci afin de pouvoir juger de la nécessité d'une assistance selon son état`},
  {code:`AA226.8`,num:8,ue:226,cours:null,desc:`de continuer à traiter le patient par oxygène médical`},
  {code:`AA226.9`,num:9,ue:226,cours:null,desc:`de transmettre, dans le respect des procédures, les informations relatives au patient et à la mission`},
];

tx(rows);
console.log('✓', rows.length, 'AA importés');